### ISSUE TITLE
Include License File from Original Project

### ISSUE THREAD

**Issue by DanWahlin** [born2net/ng2-minimal#3]
First off, nice work on adding the new routing code into the project. I just started converting my original Angular 2 JumpStart project (that this ng2-minimal project is based on - https://github.com/DanWahlin/Angular2-JumpStart) to use the latest router today and stumbled across this project. I would appreciate if you could do the following:
1. Please add back the license file provided in the original project given that the ng2-minimal project is based on my project which had a license file.
2. I'd definitely appreciate and welcome pull requests back to my original project. 

Thanks!
Dan

**Comment by born2net** [comment]
absolutely... FYI I enjoy your videos... 
doing now...

**Comment by born2net** [comment]
in fact, if you want, I can just close down the project and do a re-direct to yours if you have the router now... let me know will this be better?

**Comment by DanWahlin** [comment]
If you're able to contribute to the original project I'd definitely welcome it. I just started doing the conversion this morning and found your version which is great (haven't had time to study the new code yet but it gives me a "jumpstart"). :-) I'd love to have 1 "source of truth" for the project if possible. I haven't officially done anything with the newest router though on that project. If you don't have time I can move your modifications over, but I'd rather you get credit for the new enhancements.

**Comment by born2net** [comment]
added lic and credits and sure, let me know when you are done and will do a redirect
FYI I recommend you checkout my other 2 projects:

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

as well as:
https://github.com/born2net/studioDashboard

Regards,

Sean

**Comment by DanWahlin** [comment]
Cool - thanks Sean! I'll try to get that going today and let you know once I'm done. I'll give you credit in the check-in stuff I do. :-)

**Comment by DanWahlin** [comment]
Hey Sean. I just realized that this is actually based on the Heroes project rather than my full Angular 2 JumpStart (just has some pieces from the jumpstart project). I should've looked closer - sorry to even bug you about it.

**Comment by born2net** [comment]
ya it's a mix of the 2, no worries...
