### ISSUE TITLE
Build Errors using clone of repo

### ISSUE THREAD

**Issue by IAMtheIAM** [born2net/ng2-minimal#4]
`> npm install` (no problems)
`> tsc --watch --sourceMap`

`src/app/app.routes.ts(13,67): error TS2322: Type '({ path: string; component: typeof HeroListComponent; } | { path: string; component: typeof HeroD...' is not assignable to type 'Route[]'.
  Type '{ path: string; component: typeof HeroListComponent; } | { path: string; component: typeof HeroDe...' is not assignable to type 'Route'.
    Type '{ path: string; component: typeof CrisisCenterComponent; index: boolean; children: ({ path: strin...' is not assignable to type 'Route'.
      Object literal may only specify known properties, and 'index' does not exist in type 'Route'.
10:25:42 AM - Compilation complete. Watching for file changes.`

**Comment by born2net** [comment]
sorry but I no longer maintain this project as I migrated the code into:
https://github.com/born2net/ng2Boilerplate

**Comment by IAMtheIAM** [comment]
OK, thank you for the update. Can you please update README file on github page to let others know in big bold letters?

**Comment by born2net** [comment]
sure, done!
