### ISSUE TITLE
EXCEPTION: Can't resolve all parameters for RouterOutlet: (RouterOutletMap, ViewContainerRef, ?, name)

### ISSUE THREAD

**Issue by suma-nunna** [born2net/ng2-minimal#5]
Hi

I have clone this project. It doesn't showing any errors in npm command prompt but in the browser console it rises an exception 
**EXCEPTION: Can't resolve all parameters for RouterOutlet: (RouterOutletMap, ViewContainerRef, ?, name).**

Can anyone please resolve these issue.

Thanks.

**Comment by born2net** [comment]
please see https://github.com/born2net/ng2Boilerplate

**Comment by suma-nunna** [comment]
Thanks for your quick reply. Actually the migrated project is in RC4 but i want to use RC2 project along with Router concept.
